INSERT INTO ADDRESS_ENTITY (CEP, CITY, COMPLEMENT, NEIGHBORHOOD, NUM, STATE, STREET)
    VALUES ('30360-110', 'Belo Horizonte', 'casa', 'São Bento', '133', 'MG', 'Rua Antares');
INSERT INTO ADDRESS_ENTITY (CEP, CITY, COMPLEMENT, NEIGHBORHOOD, NUM, STATE, STREET)
    VALUES ('30330-080', 'Belo Horizonte', 'apartamento 202', 'São Pedro', '317', 'MG', 'Rua Raul Pompéia');
INSERT INTO ADDRESS_ENTITY (CEP, CITY, COMPLEMENT, NEIGHBORHOOD, NUM, STATE, STREET)
    VALUES ('02013-050', 'São Paulo', 'apto 201', 'Santana', '238', 'SP', 'Rua Carlos Escobar');
INSERT INTO ADDRESS_ENTITY (CEP, CITY, COMPLEMENT, NEIGHBORHOOD, NUM, STATE, STREET)
    VALUES ('02013-080', 'São Paulo', 'apto 103', 'Santana', '89', 'SP', 'Rua Macaiá-Mirim');

INSERT INTO DOCTOR_ENTITY (BIRTHDAY, CPF, EMAIL, FULL_NAME, GENDER, MARITAL_STATUS, PLACE_OF_BIRTH, RG, TELEPHONE, CRM, PASSWORD, SPECIALIZATION)
    VALUES (TO_DATE('01/01/1991', 'dd/mm/yyyy'), '123.456.789-10', 'medico@philips.com', 'Doque Thor', 'M', 1, 'Blumenau', '87.654.321', '(12)93456-7890', '893.687-2', 'password1', 1);
INSERT INTO DOCTOR_ENTITY (BIRTHDAY, CPF, EMAIL, FULL_NAME, GENDER, MARITAL_STATUS, PLACE_OF_BIRTH, RG, TELEPHONE, CRM, PASSWORD, SPECIALIZATION)
    VALUES (TO_DATE('02/02/1992', 'dd/mm/yyyy'), '456.789.101-23', 'medico@fleury.com', 'Mad Co.', 'F', 2, 'São Paulo', '64.591.519', '(23)94567-8901', '632.782-4', 'senha123', 1);

INSERT INTO PATIENT_ENTITY (BIRTHDAY, CPF, EMAIL, FULL_NAME, GENDER, MARITAL_STATUS, PLACE_OF_BIRTH, RG, TELEPHONE, ALLERGY_LIST, EMERGENCY_CONTACT, INSURANCE, INSURANCE_CARD_ID, INSURANCE_EXPIRATION_DATE, SPECIAL_NEEDS, ADDRESS_ID)
    VALUES (TO_DATE('03/03/1993', 'dd/mm/yyyy'), '789.101.234-56', 'paciente@gmail.com', 'João da Silva', 'M', 3, 'Rio de Janeiro', '016.893.146', '(34)95678-9012', 'Amendoim', '(56)97890-1234', 'Unimed', '45.391', TO_DATE('01/01/2024', 'dd/mm/yyyy'), 'colher sangue deitado', 1);
INSERT INTO PATIENT_ENTITY (BIRTHDAY, CPF, EMAIL, FULL_NAME, GENDER, MARITAL_STATUS, PLACE_OF_BIRTH, RG, TELEPHONE, EMERGENCY_CONTACT, SPECIAL_NEEDS, ADDRESS_ID)
    VALUES (TO_DATE('04/04/1994', 'dd/mm/yyyy'), '101.234.567-89', 'paciente@hotmail.com', 'Joana da Silva', 'F', 3, 'Rio de Janeiro', '016.893.147', '(45)96789-0123', '(34)95678-9012', 'colher sangue deitada', 1);

INSERT INTO APPOINTMENT_ENTITY (DATE_TIME, DOSAGE_AND_PRECAUTIONS, ISSUE_DESCRIPTION, MOTIVE, PRESCRIBED_MEDICATION, DOCTOR_ID, PATIENT_ID)
    VALUES (TO_DATE('28/04/2023 16:56:01', 'dd/mm/yyyy hh24:mi:ss'), '1g de 8h em 8h', 'cefaleia', 'quer dispensa médica', 'dipirona', 1, 1);
-- INSERT INTO DOCTOR_ENTITY_APPOINTMENTS VALUES (1, 1);
-- INSERT INTO PATIENT_ENTITY_APPOINTMENTS VALUES (1, 1);

INSERT INTO APPOINTMENT_ENTITY (DATE_TIME, DOSAGE_AND_PRECAUTIONS, ISSUE_DESCRIPTION, MOTIVE, PRESCRIBED_MEDICATION, DOCTOR_ID, PATIENT_ID)
    VALUES (TO_DATE('28/04/2023 17:26:01', 'dd/mm/yyyy hh24:mi:ss'), '2,5mg durante a crise', 'enxaqueca', 'visão em túnel', 'cloridrato de naratriptana', 2, 1);
-- INSERT INTO DOCTOR_ENTITY_APPOINTMENTS VALUES (2, 2);
-- INSERT INTO PATIENT_ENTITY_APPOINTMENTS VALUES (1, 2);

INSERT INTO APPOINTMENT_ENTITY (DATE_TIME, DOSAGE_AND_PRECAUTIONS, ISSUE_DESCRIPTION, MOTIVE, PRESCRIBED_MEDICATION, DOCTOR_ID, PATIENT_ID)
    VALUES (TO_DATE('28/04/2023 17:36:01', 'dd/mm/yyyy hh24:mi:ss'), '500mg de 8h em 8h até 5 dias', 'cólica menstrual', 'cólicas incapacitantes', 'ácido mefenâmico', 1, 2);
-- INSERT INTO DOCTOR_ENTITY_APPOINTMENTS VALUES (1, 3);
-- INSERT INTO PATIENT_ENTITY_APPOINTMENTS VALUES (2, 3);

INSERT INTO APPOINTMENT_ENTITY (DATE_TIME, DOSAGE_AND_PRECAUTIONS, ISSUE_DESCRIPTION, MOTIVE, PRESCRIBED_MEDICATION, DOCTOR_ID, PATIENT_ID)
    VALUES (TO_DATE('28/04/2023 18:35:01', 'dd/mm/yyyy hh24:mi:ss'), '1 comprimido de antibiótico a cada 8 horas por 7 dias', 'apendicite', 'dores no abdômen', 'amoxicilina', 2, 2);
-- INSERT INTO DOCTOR_ENTITY_APPOINTMENTS VALUES (2, 4);
-- INSERT INTO PATIENT_ENTITY_APPOINTMENTS VALUES (2, 4);

INSERT INTO EXAM_ENTITY (DATE_TIME, FILE_URL, LABORATORY, NAME, RESULTS, TYPE, DOCTOR_ID, PATIENT_ID)
    VALUES (TO_DATE('28/04/2023 08:21:06', 'dd/mm/yyyy hh24:mi:ss'), 'https://www.youtube.com', 'Fleury', 't4 livre', 'normal', 'sangue', 1, 1);
-- INSERT INTO DOCTOR_ENTITY_EXAMS VALUES (1, 1);
-- INSERT INTO PATIENT_ENTITY_EXAMS VALUES (1, 1);

INSERT INTO EXAM_ENTITY (DATE_TIME, FILE_URL, LABORATORY, NAME, RESULTS, TYPE, DOCTOR_ID, PATIENT_ID)
    VALUES (TO_DATE('28/04/2023 08:21:15', 'dd/mm/yyyy hh24:mi:ss'), 'https://www.youtube.com', 'Fleury', 'hemograma', 'normal', 'sangue', 1, 2);
-- INSERT INTO DOCTOR_ENTITY_EXAMS VALUES (1, 2);
-- INSERT INTO PATIENT_ENTITY_EXAMS VALUES (2, 2);

INSERT INTO EXAM_ENTITY (DATE_TIME, FILE_URL, LABORATORY, NAME, RESULTS, TYPE, DOCTOR_ID, PATIENT_ID)
    VALUES (TO_DATE('28/04/2023 08:22:06', 'dd/mm/yyyy hh24:mi:ss'), 'https://www.youtube.com', 'Fleury', 'glicemia', 'síndrome metabólica', 'sangue', 2, 1);
-- INSERT INTO DOCTOR_ENTITY_EXAMS VALUES (2, 3);
-- INSERT INTO PATIENT_ENTITY_EXAMS VALUES (1, 3);

INSERT INTO EXAM_ENTITY (DATE_TIME, FILE_URL, LABORATORY, NAME, RESULTS, TYPE, DOCTOR_ID, PATIENT_ID)
    VALUES (TO_DATE('28/04/2023 08:23:20', 'dd/mm/yyyy hh24:mi:ss'), 'https://www.youtube.com', 'Fleury', 'lipidograma', 'colesterol alto', 'sangue', 2, 2);
-- INSERT INTO DOCTOR_ENTITY_EXAMS VALUES (2, 4);
-- INSERT INTO PATIENT_ENTITY_EXAMS VALUES (2, 4);
